[profile.default]
src = "src"
out = "out"
libs = ["lib"]


remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/", 
    "ENSMetadataStandard=lib/ENSMetadataStandard/src/"
]

# Include more configuration options here
# Reference: https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[dependencies]
